### ISSUE TITLE
Combinar background-image y background-color

### ISSUE THREAD

**Issue by Max131** [Max131/notes#10]
## Combinar background image y color

Con la propiedad `background-blend-mode` se puede mezclar la imagen y color de fondo para lograr un efecto más oscuro o claro con el color definido.

```css

.div{
  min-height: 80vh;
  background: rgba(0,0,0, 0.5) url('https://picsum.photos/600') no-repeat center/cover;
  background-blend-mode: darken /* normal, darken, luminosity, inherit, unset */
}

```
Similares: [`Css blend modes`](https://codepen.io/Kseso/pen/isJGu?editors=1100)
