### ISSUE TITLE
background-clip

### ISSUE THREAD

**Issue by Max131** [Max131/notes#4]
## background-clip

`background-clip` recorta el fondo en función de la distancia del borde, padding o contenido, puede servir para crear espacios entre el background y el border si la necesidad de añadir capas adicionales.

```css
.fondo-recortado{
  padding: 4rem;
  background: whitesmoke url('https://placeimg.com/800/600/any') no-repeat center / cover;
  background-clip: content-box; /* border-box, padding-box*/
}

```
