### ISSUE TITLE
Anulación de estilos en enlaces

### ISSUE THREAD

**Issue by Max131** [Max131/notes#9]
## Anulación de estilos en enlaces

Los estilos en los elementos de enlace **`a`** pueden llegar a ser anulados si no siguen el orden LVHA, es decir, ":link", ":visited", ":hover" y ":active". En el siguiente ejemplo, el selector `a:hover` desactivara al selector `a:active` al no ser definidos en el orden adecuado (LVHA). por el contrario, si se invierte el orden, ambos funcionarán sin problema. 

```css

a:active{
 color: red
}

a:hover{
 color: golden;
}

```
Referencia: [CSS Tricks](https://css-tricks.com/almanac/selectors/a/active/)
